language: erlang
services:
  - rabbitmq
before_script:
  - sudo rabbitmqctl add_vhost /test
  - sudo rabbitmqctl add_user test test
  - sudo rabbitmqctl set_permissions -p /test test '.*' '.*' '.*'
  - rebar compile
script: rebar compile && rebar skip_deps=true eunit
otp_release:
  - 17.3
  - 17.0
  - R16B03-1
  - R16B02
